# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9b04b75dce6ec27c88b2596dc6b026fffa5ccd9816672367896636502a61573b70330eb058302dbfd6446035ae8bf0a0713c4c5daaec226fb088d9b6664d36d

test:
  secret_key_base: e740958fbc9f888fddcc1c12bd96bd4648f97273871bdcf1d0674e213fd4ae32203b7d57d2077bc1ccbe85c231abc6179e896698685f4c7939194b1ccbdd0093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
